import express from'express';import cors from'cors';import dotenv from'dotenv';import helmet from'helmet';import rateLimit from'express-rate-limit';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import crypto from'crypto';import {PrismaClient}from'@prisma/client';import {getSafeLessonContent,getTask}from'./lessons/content.js';import {sendVerificationEmail,sendPasswordResetEmail}from'./email.js';dotenv.config();
const app=express(),db=new PrismaClient(),PORT=process.env.PORT||4000;
app.use(helmet());app.use(cors({origin:process.env.FRONTEND_URL||true}));app.use(express.json({limit:'1mb'}));app.use('/api/auth',rateLimit({windowMs:15*60e3,max:30}));
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),rand=()=>crypto.randomBytes(32).toString('base64url'),access=u=>jwt.sign({sub:u.id,email:u.email},process.env.JWT_SECRET,{expiresIn:'15m'});
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'UNAUTHORIZED'})}}
function checkAnswer(task,body){
  if(task.type==='formula'){const f=String(body.formula||'').replace(/\s/g,'').toUpperCase();return task.answers.map(a=>a.replace(/\s/g,'').toUpperCase()).includes(f)}
  if(task.type==='multiple_choice'){return body.optionId===task.correctOptionId}
  if(task.type==='click_cell'){return String(body.cell||'').toUpperCase()===String(task.target).toUpperCase()}
  return false
}
function answerInput(task,body){
  if(task.type==='formula')return{formula:body.formula};
  if(task.type==='multiple_choice')return{optionId:body.optionId};
  if(task.type==='click_cell')return{cell:body.cell};
  return{}
}
app.get('/healthz',async(req,res)=>{try{await db.$queryRaw`SELECT 1`;res.json({status:'ok'})}catch{res.status(503).json({status:'degraded'})}});
app.post('/api/auth/register',async(req,res)=>{const{name,email,password,language}=req.body||{};if(!name||!email||String(password).length<8)return res.status(400).json({error:'INVALID_INPUT'});if(await db.user.findUnique({where:{email}}))return res.status(409).json({error:'EMAIL_EXISTS'});const lang=language==='ar'?'ar':'en';const u=await db.user.create({data:{name,email,passwordHash:await bcrypt.hash(password,12),language:lang}});const raw=rand();await db.emailVerificationToken.create({data:{userId:u.id,tokenHash:hash(raw),expiresAt:new Date(Date.now()+864e5)}});try{await sendVerificationEmail(u,raw)}catch(e){console.error('verification email failed',e)}const dev=process.env.NODE_ENV!=='production'?{devVerificationUrl:`${process.env.FRONTEND_URL||'http://localhost:5173'}/?verify=${encodeURIComponent(raw)}`}:{};res.status(201).json({user:{id:u.id,email:u.email,language:u.language},verificationRequired:true,...dev})});
app.post('/api/auth/verify-email',async(req,res)=>{const x=await db.emailVerificationToken.findUnique({where:{tokenHash:hash(req.body?.token||'')}});if(!x||x.usedAt||x.expiresAt<new Date())return res.status(400).json({error:'INVALID_TOKEN'});await db.$transaction([db.user.update({where:{id:x.userId},data:{emailVerified:true}}),db.emailVerificationToken.update({where:{id:x.id},data:{usedAt:new Date()}})]);res.json({verified:true})});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body||{},u=await db.user.findUnique({where:{email}});if(!u||!await bcrypt.compare(password||'',u.passwordHash))return res.status(401).json({error:'INVALID_CREDENTIALS'});if(!u.emailVerified)return res.status(403).json({error:'EMAIL_NOT_VERIFIED'});const raw=rand();await db.refreshSession.create({data:{userId:u.id,tokenHash:hash(raw),expiresAt:new Date(Date.now()+30*864e5)}});res.json({accessToken:access(u),refreshToken:raw,user:{id:u.id,name:u.name,email:u.email,language:u.language}})});
app.post('/api/auth/refresh',async(req,res)=>{const s=await db.refreshSession.findUnique({where:{tokenHash:hash(req.body?.refreshToken||'')},include:{user:true}});if(!s||s.revokedAt||s.expiresAt<new Date())return res.status(401).json({error:'INVALID_REFRESH'});await db.refreshSession.update({where:{id:s.id},data:{revokedAt:new Date()}});const raw=rand();await db.refreshSession.create({data:{userId:s.userId,tokenHash:hash(raw),expiresAt:new Date(Date.now()+30*864e5)}});res.json({accessToken:access(s.user),refreshToken:raw})});
app.post('/api/auth/request-password-reset',async(req,res)=>{const email=req.body?.email;const u=email?await db.user.findUnique({where:{email}}):null;let devResetUrl;if(u){const raw=rand();await db.passwordResetToken.create({data:{userId:u.id,tokenHash:hash(raw),expiresAt:new Date(Date.now()+3600e3)}});try{await sendPasswordResetEmail(u,raw)}catch(e){console.error('password reset email failed',e)}if(process.env.NODE_ENV!=='production')devResetUrl=`${process.env.FRONTEND_URL||'http://localhost:5173'}/?reset=${encodeURIComponent(raw)}`}res.json({requested:true,...(devResetUrl?{devResetUrl}:{})})});
app.post('/api/auth/reset-password',async(req,res)=>{const{token,newPassword}=req.body||{};if(!token||String(newPassword).length<8)return res.status(400).json({error:'INVALID_INPUT'});const x=await db.passwordResetToken.findUnique({where:{tokenHash:hash(token)}});if(!x||x.usedAt||x.expiresAt<new Date())return res.status(400).json({error:'INVALID_TOKEN'});await db.$transaction([db.user.update({where:{id:x.userId},data:{passwordHash:await bcrypt.hash(newPassword,12)}}),db.passwordResetToken.update({where:{id:x.id},data:{usedAt:new Date()}}),db.refreshSession.updateMany({where:{userId:x.userId,revokedAt:null},data:{revokedAt:new Date()}})]);res.json({reset:true})});
app.put('/api/me/language',auth,async(req,res)=>{const language=req.body?.language==='ar'?'ar':'en';const u=await db.user.update({where:{id:req.user.sub},data:{language}});res.json({language:u.language})});
app.get('/api/lessons',auth,async(req,res)=>{const lang=req.query.lang==='ar'?'ar':'en';const rows=await db.lesson.findMany({orderBy:{sortOrder:'asc'}});res.json(rows.map(l=>({id:l.id,sortOrder:l.sortOrder,title:lang==='ar'&&l.titleAr?l.titleAr:l.title,area:lang==='ar'&&l.areaAr?l.areaAr:l.area})))});
app.get('/api/progress',auth,async(req,res)=>res.json(await db.learnerProgress.findMany({where:{userId:req.user.sub}})));
app.get('/api/lessons/:id/content',auth,async(req,res)=>{const lang=req.query.lang==='ar'?'ar':'en';const c=getSafeLessonContent(req.params.id,lang);if(!c)return res.status(404).json({error:'NOT_FOUND'});res.json(c)});
app.get('/api/lessons/:id/session',auth,async(req,res)=>res.json(await db.lessonSession.findUnique({where:{userId_lessonId:{userId:req.user.sub,lessonId:req.params.id}}})));
app.put('/api/lessons/:id/session',auth,async(req,res)=>{const x=req.body||{},s=await db.lessonSession.upsert({where:{userId_lessonId:{userId:req.user.sub,lessonId:req.params.id}},create:{userId:req.user.sub,lessonId:req.params.id,state:x.state||{},attempts:x.attempts||0,hintsUsed:x.hintsUsed||0},update:{state:x.state||{},attempts:x.attempts||0,hintsUsed:x.hintsUsed||0}});await db.learnerProgress.upsert({where:{userId_lessonId:{userId:req.user.sub,lessonId:req.params.id}},create:{userId:req.user.sub,lessonId:req.params.id,status:'IN_PROGRESS'},update:{status:'IN_PROGRESS'}});res.json(s)});
app.post('/api/lessons/:id/attempt',auth,async(req,res)=>{const taskId=req.body?.taskId,task=getTask(req.params.id,taskId);if(!task)return res.status(400).json({error:'UNKNOWN_TASK'});const correct=checkAnswer(task,req.body||{});const a=await db.taskAttempt.create({data:{userId:req.user.sub,lessonId:req.params.id,taskId:String(taskId),attemptNo:Number(req.body?.attemptNo||1),correct,input:answerInput(task,req.body||{})}});res.json({correct,attemptId:a.id})});
app.post('/api/lessons/:id/complete',auth,async(req,res)=>res.json(await db.learnerProgress.upsert({where:{userId_lessonId:{userId:req.user.sub,lessonId:req.params.id}},create:{userId:req.user.sub,lessonId:req.params.id,status:'COMPLETED',score:Number(req.body?.score||100)},update:{status:'COMPLETED',score:Number(req.body?.score||100)}})));
app.get('/api/achievements',auth,async(req,res)=>{const p=await db.learnerProgress.findMany({where:{userId:req.user.sub,status:'COMPLETED'}}),d=p.map(x=>x.lessonId);res.json([{name:'First Step',earned:d.length>=1},{name:'Formula Builder',earned:d.includes('lesson-6')},{name:'Halfway There',earned:d.length>=9},{name:'Excel Ready',earned:d.length>=17}])});
app.post('/api/certificates/issue',auth,async(req,res)=>{if(await db.learnerProgress.count({where:{userId:req.user.sub,status:'COMPLETED'}})<17)return res.status(400).json({error:'NOT_ELIGIBLE'});const c=await db.certificate.upsert({where:{userId:req.user.sub},update:{},create:{userId:req.user.sub,certificateId:`SKL-${new Date().getFullYear()}-${rand().slice(0,10).toUpperCase()}`,verificationCode:rand().slice(0,12).toUpperCase()}});res.status(201).json(c)});
app.get('/api/certificates/verify/:code',async(req,res)=>{const c=await db.certificate.findUnique({where:{verificationCode:req.params.code},include:{user:{select:{name:true}}}});if(!c)return res.status(404).json({valid:false});res.json({valid:true,certificateId:c.certificateId,learner:c.user.name,issuedAt:c.issuedAt})});
app.listen(PORT,()=>console.log(`Skillora API :${PORT}`));